version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54320:5432"

volumes:
  pgdata:
