"""added reset password token

Revision ID: f3a51440d2db
Revises: 60c26acb7097
Create Date: 2024-10-17 20:45:50.156505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a51440d2db'
down_revision: Union[str, None] = '60c26acb7097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_token', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_token')
    # ### end Alembic commands ###
